# Makefile generated by BUILD.CMD V2.3.3
# 4 May 2004 at 11:18:24
# Mode WC

.SUFFIXES:
.SUFFIXES: .c .cpp .rc .obj .lib .res .dll .exe

# Compiler
CC=wcl386 -i=..\include;..\pcre -zq -zm -6r -bm -ot -s
LNK=-k327680 -"op el"

# Librarian
LIBRARIAN=wlib

# Resource compiler
RC=rc -i ..\include;..\pcre -x2

# Rules

vpath %.obj .\obj
vpath %.lib .\obj
vpath %.exe .\obj
vpath %.dll .\obj
vpath %.cpp .\source
vpath %.res .\obj
vpath %.rc .\source
vpath %.c .\source
vpath %.h .\include
vpath %.hpp .\include

.c.obj:
	@echo $(subst /,\,.$<)
	@cd .\obj & $(CC) -c $(subst /,\,.$<)

.cpp.obj:
	@echo $(subst /,\,.$<)
	@cd .\obj & $(CC) -c $(subst /,\,.$<)

.rc.res:
	@echo ..\obj\$(subst /,\,$@)
	@cd .\source & $(RC) -r $(subst /,\,.$<) ..\obj\$(subst /,\,$@)

# Libary dependencies

OBJS = 
OBJS +=  _ctype.obj bcommand.obj bdraw.obj bindery.obj block.obj boxcoll.obj
OBJS +=  bracket.obj bsearch.obj buffer.obj bundo.obj clipbrd.obj collect.obj
OBJS +=  compile.obj cp_cvt.obj cursor.obj cvt.obj dialog.obj dict.obj
OBJS +=  dispatch.obj editbox.obj editline.obj fio.obj fntable.obj history.obj
OBJS +=  idcoll.obj keycoll.obj launch.obj line.obj palette.obj pars_asm.obj
OBJS +=  pars_cpp.obj pars_htm.obj pars_mk.obj pars_ml.obj pars_pas.obj
OBJS +=  pars_pl.obj pars_rx.obj pars_tex.obj parser.obj pipe.obj pmclip.obj
OBJS +=  profile.obj rx.obj search.obj sort.obj stddlg.obj vio.obj

# Targets 
all : prerequisite  clip.exe fed.exe kbshow.exe

prerequisite:
	@cd pcre & call mk.cmd WC & cd ..

common.lib : $(OBJS)
	-@del .\obj\common.lib >nul 2>nul
	@echo $(subst /,\,$@)
	@cd .\obj & $(LIBRARIAN) common.lib @..\library.rsp >nul

clip.exe : common.lib clip.obj
	@echo $(subst /,\,$@)
	@cd .\obj & wlink @clip.lnk

fed.exe : common.lib fed.obj
	@echo $(subst /,\,$@)
	@cd .\obj & wlink @fed.lnk

kbshow.exe : common.lib kbshow.obj
	@echo $(subst /,\,$@)
	@cd .\obj & wlink @kbshow.lnk


# Individual dependencies

_ctype.obj  : _ctype.h   common.h   cvt.h      version.h  vio.h      _ctype.cpp
bcommand.obj: _ctype.h   bindery.h  boxcoll.h  buffer.h   collect.h  common.h   cvt.h      dialog.h   dict.h     editbox.h  fio.h      history.h  idcoll.h   keycoll.h  keynames.h line.h     parser.h   pipe.h     stddlg.h   version.h  vio.h      bcommand.cpp
bdraw.obj   : _ctype.h   buffer.h   collect.h  common.h   cvt.h      dialog.h   dict.h     idcoll.h   line.h     parser.h   version.h  vio.h      bdraw.cpp
bindery.obj : _ctype.h   bindery.h  boxcoll.h  buffer.h   collect.h  common.h   cvt.h      dialog.h   dict.h     editbox.h  fio.h      history.h  idcoll.h   keycoll.h  line.h     parser.h   pipe.h     version.h  vio.h      bindery.cpp
block.obj   : _ctype.h   buffer.h   collect.h  common.h   cvt.h      dialog.h   dict.h     idcoll.h   line.h     parser.h   version.h  vio.h      block.cpp
boxcoll.obj : _ctype.h   bindery.h  boxcoll.h  buffer.h   collect.h  common.h   cvt.h      dialog.h   dict.h     editbox.h  fio.h      history.h  idcoll.h   keycoll.h  keynames.h line.h     parser.h   pipe.h     rx.h       stddlg.h   version.h  vio.h      boxcoll.cpp
bracket.obj : _ctype.h   buffer.h   collect.h  common.h   cvt.h      dialog.h   dict.h     idcoll.h   line.h     parser.h   version.h  vio.h      bracket.cpp
bsearch.obj : _ctype.h   _regex.h   _search.h  buffer.h   collect.h  common.h   cvt.h      dialog.h   dict.h     idcoll.h   line.h     parser.h   version.h  vio.h      bsearch.cpp
buffer.obj  : _ctype.h   buffer.h   collect.h  common.h   cvt.h      dialog.h   dict.h     idcoll.h   line.h     parser.h   version.h  vio.h      buffer.cpp
bundo.obj   : _ctype.h   buffer.h   collect.h  common.h   cvt.h      dialog.h   dict.h     idcoll.h   line.h     parser.h   version.h  vio.h      bundo.cpp
clip.obj    : clip.cpp
clipbrd.obj : _ctype.h   buffer.h   collect.h  common.h   cvt.h      dialog.h   dict.h     idcoll.h   line.h     parser.h   version.h  vio.h      clipbrd.cpp
collect.obj : collect.h  version.h  collect.cpp
compile.obj : _ctype.h   bindery.h  boxcoll.h  buffer.h   collect.h  common.h   cvt.h      dialog.h   dict.h     editbox.h  history.h  idcoll.h   keycoll.h  line.h     parser.h   pipe.h     version.h  vio.h      compile.cpp
cp_cvt.obj  : cp_cvt.cpp
cursor.obj  : _ctype.h   buffer.h   collect.h  common.h   cvt.h      dialog.h   dict.h     idcoll.h   line.h     parser.h   version.h  vio.h      cursor.cpp
cvt.obj     : _ctype.h   common.h   cvt.h      version.h  vio.h      cvt.cpp
dialog.obj  : _ctype.h   collect.h  common.h   cvt.h      dialog.h   keynames.h version.h  vio.h      dialog.cpp
dict.obj    : _ctype.h   collect.h  common.h   cvt.h      dict.h     version.h  vio.h      dict.cpp
dispatch.obj: _ctype.h   bindery.h  boxcoll.h  buffer.h   collect.h  common.h   cvt.h      dialog.h   dict.h     editbox.h  history.h  idcoll.h   keycoll.h  keynames.h line.h     parser.h   pipe.h     version.h  vio.h      dispatch.cpp
editbox.obj : _ctype.h   bindery.h  boxcoll.h  buffer.h   collect.h  common.h   cvt.h      dialog.h   dict.h     editbox.h  fio.h      history.h  idcoll.h   keycoll.h  line.h     parser.h   pipe.h     stddlg.h   version.h  vio.h      editbox.cpp
editline.obj: _ctype.h   buffer.h   collect.h  common.h   cvt.h      dialog.h   dict.h     idcoll.h   keynames.h line.h     parser.h   version.h  vio.h      editline.cpp
fed.obj     : _ctype.h   bindery.h  boxcoll.h  buffer.h   collect.h  common.h   cvt.h      dialog.h   dict.h     editbox.h  fio.h      history.h  idcoll.h   keycoll.h  keynames.h line.h     parser.h   pipe.h     pmproc.h   stddlg.h   version.h  vio.h      fed.cpp
fio.obj     : _ctype.h   _regex.h   _search.h  collect.h  common.h   cvt.h      dict.h     fio.h      idcoll.h   line.h     parser.h   version.h  vio.h      fio.cpp
fntable.obj : _ctype.h   bindery.h  boxcoll.h  buffer.h   collect.h  common.h   cvt.h      dialog.h   dict.h     editbox.h  history.h  idcoll.h   keycoll.h  line.h     parser.h   pipe.h     version.h  vio.h      fntable.cpp
history.obj : collect.h  common.h   cvt.h      dialog.h   history.h  vio.h      history.cpp
idcoll.obj  : _ctype.h   collect.h  common.h   cvt.h      dialog.h   dict.h     idcoll.h   line.h     parser.h   version.h  vio.h      idcoll.cpp
kbshow.obj  : keynames.h vio.h      kbshow.cpp
keycoll.obj : _ctype.h   bindery.h  boxcoll.h  buffer.h   collect.h  common.h   cvt.h      dialog.h   dict.h     editbox.h  history.h  idcoll.h   keycoll.h  line.h     parser.h   pipe.h     version.h  vio.h      keycoll.cpp
launch.obj  : _ctype.h   _regex.h   _search.h  buffer.h   collect.h  common.h   cvt.h      dialog.h   dict.h     fio.h      idcoll.h   line.h     parser.h   version.h  vio.h      launch.cpp
line.obj    : _ctype.h   buffer.h   collect.h  common.h   cvt.h      dialog.h   dict.h     idcoll.h   line.h     parser.h   version.h  vio.h      line.cpp
palette.obj : _ctype.h   bindery.h  boxcoll.h  buffer.h   collect.h  common.h   cvt.h      dialog.h   dict.h     editbox.h  history.h  idcoll.h   keycoll.h  line.h     parser.h   pipe.h     version.h  vio.h      palette.cpp
pars_asm.obj: _ctype.h   collect.h  common.h   cvt.h      dict.h     parser.h   version.h  vio.h      pars_asm.cpp
pars_cpp.obj: _ctype.h   collect.h  common.h   cvt.h      dict.h     parser.h   version.h  vio.h      pars_cpp.cpp
pars_htm.obj: _ctype.h   collect.h  common.h   cvt.h      dict.h     parser.h   version.h  vio.h      pars_htm.cpp
pars_mk.obj : _ctype.h   collect.h  common.h   cvt.h      dict.h     parser.h   version.h  vio.h      pars_mk.cpp
pars_ml.obj : _ctype.h   collect.h  common.h   cvt.h      dict.h     parser.h   version.h  vio.h      pars_ml.cpp
pars_pas.obj: _ctype.h   collect.h  common.h   cvt.h      dict.h     parser.h   version.h  vio.h      pars_pas.cpp
pars_pl.obj : _ctype.h   collect.h  common.h   cvt.h      dict.h     parser.h   version.h  vio.h      pars_pl.cpp
pars_rx.obj : _ctype.h   collect.h  common.h   cvt.h      dict.h     parser.h   version.h  vio.h      pars_rx.cpp
pars_tex.obj: _ctype.h   collect.h  common.h   cvt.h      dict.h     parser.h   version.h  vio.h      pars_tex.cpp
parser.obj  : _ctype.h   collect.h  common.h   cvt.h      dict.h     fio.h      parser.h   version.h  vio.h      parser.cpp
pipe.obj    : pipe.h     version.h  pipe.cpp
pmclip.obj  : _ctype.h   buffer.h   collect.h  common.h   cvt.h      dialog.h   dict.h     idcoll.h   line.h     parser.h   pmproc.h   vio.h      pmclip.cpp
profile.obj : _ctype.h   bindery.h  boxcoll.h  buffer.h   collect.h  common.h   cvt.h      dialog.h   dict.h     editbox.h  fio.h      history.h  idcoll.h   keycoll.h  line.h     parser.h   pipe.h     stddlg.h   version.h  vio.h      profile.cpp
rx.obj      : _ctype.h   _regex.h   _search.h  bindery.h  boxcoll.h  buffer.h   collect.h  common.h   cvt.h      dialog.h   dict.h     editbox.h  fio.h      history.h  idcoll.h   keycoll.h  keynames.h line.h     parser.h   pipe.h     stddlg.h   version.h  vio.h      rx.cpp
search.obj  : _ctype.h   _regex.h   _search.h  collect.h  common.h   cvt.h      dict.h     idcoll.h   line.h     parser.h   version.h  vio.h      search.cpp
sort.obj    : _ctype.h   buffer.h   collect.h  common.h   cvt.h      dialog.h   dict.h     idcoll.h   line.h     parser.h   version.h  vio.h      sort.cpp
stddlg.obj  : _ctype.h   bindery.h  boxcoll.h  buffer.h   collect.h  common.h   cvt.h      dialog.h   dict.h     editbox.h  fio.h      history.h  idcoll.h   keycoll.h  keynames.h line.h     parser.h   pipe.h     stddlg.h   version.h  vio.h      stddlg.cpp
vio.obj     : _ctype.h   common.h   cvt.h      keynames.h pmproc.h   version.h  vio.h      vio.cpp

# End
